[WIP] Add new method for adding ConsoleYAMLSamples
atlasmap/atlasmap-operator pull request #14
Opened 2020-03-31 20:02 UTC by myeung18

Signed-off-by: Marco Yeung <myeung@redhat.com>

2020-04-01 07:10 UTC, jamesnetherton requested changes
I added a few review comments. In addition to those, it'd be nice to have a test case to verify that the `ConsoleYAMLSample` was created (if possible). There are some existing tests in `test/e2e`.

2020-04-01 07:10 UTC, jamesnetherton commented on deploy/crs/atlasmap_cr.yaml
> +  # limitMemory: 512Mi
Given that we only really need 1 example at present, maybe having a dedicated `crs` directory is unnecessary. I'd prefer to not duplicate existing content in `deploy/crds/atlasmap_cr.yaml`.

2020-04-01 07:10 UTC, jamesnetherton commented on pkg/apis/addtoscheme_atlasmap_v1alpha1.go
> +	AddToSchemes = append(AddToSchemes, v1alpha1.SchemeBuilder.AddToScheme, consolev1.Install)
This operator works on both vanilla Kubernetes and OpenShift. So we should probably only do this if running in an environment that supports this.

2020-04-01 07:10 UTC, jamesnetherton commented on pkg/controller/atlasmap/webconsole.go
> +	box := packr.New("cryamlsamples", "../../../deploy/crs")
Related to my earlier comment. Since there's only one example, maybe this can all be simplified to just load the single CR example YAML.

2020-04-01 07:10 UTC, jamesnetherton commented on pkg/controller/atlasmap/atlasmap_controller.go
> +	r.createConsoleYAMLSamples()
We only want to do this on OpenShift versions that support `ConsoleYAMLSamples`.

2020-04-01 21:24 UTC, bmozaffa commented on deploy/crs/atlasmap_cr.yaml
> +  # limitMemory: 512Mi
Question about that... is your 1 example the same as the default that you fill in, within your CSV? If yes, then I'm guessing you don't need the PR at all.

2020-04-02 06:17 UTC, jamesnetherton commented on deploy/crs/atlasmap_cr.yaml
> +  # limitMemory: 512Mi
Yes, exactly. I was going to suggest that maybe we don't actually need the PR at all.

If in future, the operator needs to support additional CRDs then we can think about additional examples. But for now, things are so simple that its maybe not worth having `ConsoleYAMLSample`.

2020-04-02 13:09 UTC, closed without merging